### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by crysehillmes** [kurisuxx/android_kernel_samsung_klimtlte#1]
Hello kurisuxx,
I'm new to android rom develop and I have a few questions needs your help, could you please help me?
The first is I have a Chinese TD-LTE version klimtlte (in build.prop device is called klimtlte but name is klimtltetdzc), could I use your kernel directly?
The second is how can I generate vender/device from the Samsung official opensource code?
Hope you can help me.
Thanks!

**Comment by kurisuxx** [comment]
_hi tyk5555 https://github.com/tyk5555,_
_im new to android rom development too but if i can help then i will._
_the kernel is the one from the samsung official opensource website so this
should work for you,_
_im not to sure how you could generate the vendor/device from the official
samsung code as i have not tried this yet._
_may i ask which version of android you are trying to work with?_

**Comment by crysehillmes** [comment]
Hi kurisuxx,
Thanks for your reply!
Now I know where to get the kernel source from your answer, today I downloaded t705c kernel source from Samsung open source center. ☺
I'm trying to port cm-12.0 to my t705c, because I don't like the stock touchwiz system.
I searched for many posts and cyanogenmod wiki but still don't know how to get the proper vendor/device projects. t705 and t705c have almost same hardwares except radio chip, according to cm wiki, seems I can try t705 device/vendor projects? Or any other ways? How did the first author create klimtlte device/vendor projects?
Look forward to your favourable reply.
Thanks.

**Comment by crysehillmes** [comment]
After reading the t705 codes and commit history, tomorrow morning I'll try to build it first, hope it could run. I find that exynos5420 do not support tdlte itself, seems there are another baseband chip, no idea what it is.

**Comment by schwabe93** [comment]
Have you build it yet for the LTE version?

**Comment by crysehillmes** [comment]
Build successfully without any error, but still have some issues:
1. It could not be flashed with klimtwifi CWM Recovery and TWRP, says update zip is for klimtlte, so it seems I have to build a klimtlte recovery.
2. With recovery.img built in $OUT directory the device could not get into recovery, still looking for the causes.

Are there anyway to avoid device name and zip device name check?
And how to build the recovery correctly?

**Comment by arvedviehweger** [comment]
I would like to start building CM13 for my T705. I donwloaded the official Cyanogenmod device files and vendor files. Compiled everything succesfully and flashed it. It's was stuck on the Bootloader. I don't know if I have to change the kernel (I used the Deathly 5.1 Kernel Config and it's sources) or the bootloader. Does anyone know what the problem could be?
